### ISSUE TITLE
PUV profile: multiple properties of the same kind can exist for a term

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#103]
PUV profile: multiple properties of the same kind can exist for a term:
select * where { <http://vocab.nerc.ac.uk/collection/A05/current/EV_SEATEMP/> ?b ?c .}

returns 

**https://w3id.org/env/puv#property>** | <http://vocab.nerc.ac.uk/collection/S06/current/S0600082/>
-- | --
**<https://w3id.org/env/puv#property>** | <http://vocab.nerc.ac.uk/collection/S06/current/S0600160/>
 <**https://w3id.org/env/puv#property>** | <http://vocab.nerc.ac.uk/collection/S06/current/S0600161/>
 <https://w3id.org/env/puv#statistic> | <http://vocab.nerc.ac.uk/collection/S07/current/S0700006/>
 <https://w3id.org/env/puv#matrix> | <http://vocab.nerc.ac.uk/collection/S26/current/MAT00640/>

puv:property appears 3 times in sparql but only once in html

RDF, Turtle and json look good.

**Comment by nicholascar** [comment]
Done in Commit https://github.com/surroundaustralia/VocPrez-theme-nvs/commit/3328a8fee124ae4eebc735a41f5d4de9859ad466

![image](https://user-images.githubusercontent.com/7321872/124429069-c2603680-ddb0-11eb-87f6-aea74ad784af.png)
