### ISSUE TITLE
https://vocabdev.nerc.ac.uk/standard_name/acoustic_signal_roundtrip_travel_time_in_sea_water/

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#104]
https://vocabdev.nerc.ac.uk/standard_name/ in HTML loads all the concepts without the trailing slash. 
When a user clicks on a concept e.g. https://vocab.nerc.ac.uk/standard_name/acoustic_signal_roundtrip_travel_time_in_sea_water/
it gives an internal error. We force the trailing slash in the end and that probably results in problems in VocPrez.

**Comment by nicholascar** [comment]
Fixed in Commit https://github.com/surroundaustralia/VocPrez-theme-nvs/commit/ef5e9f225b221f52805f3ccc7cd9fb688bbd3cef
