### ISSUE TITLE
Concept RDF is missing versioning information 

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#105]
This part is missed in versioning of concepts:
<pav:hasVersionrdf:resource="http://vocab.nerc.ac.uk/collection/P01/current/ALATGP01/2/" >
</pav:hasVersion>
	<pav:hasVersionrdf:resource="http://vocab.nerc.ac.uk/collection/P01/current/ALATGP01/1/" >
</pav:hasVersion>

Looking at http://vocab.nerc.ac.uk/collection/P01/current/ALATGP01/

**Comment by alko-k** [comment]
@nicholascar  this is still an open ticket for the new Version of vocprez

**Comment by nicholascar** [comment]
The triplestore is missing the triple `<CONCEPT> pav:version "VERSION" .`. This needs to be added and the VocPrez will automatically pick it up and display it.

**Comment by nicholascar** [comment]
See http://vocab.nerc.ac.uk/sparql/sparql?query=PREFIX%20dc%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20dce%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20pav%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fpav%2F%3E%0APREFIX%20prov%3A%20%3Chttps%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX%20void%3A%20%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0A%0ADESCRIBE%20%3Chttp%3A%2F%2Fvocab.nerc.ac.uk%2Fcollection%2FP01%2Fcurrent%2FALATGP01%2F%3E

**Comment by nicholascar** [comment]
Done, the query above shows that `pav:hasVersion` is present.

**Comment by alko-k** [comment]
Yes, this is also added in :-)
