### ISSUE TITLE
nvs.surroundaustralia.com/scheme/EMODNET_PEST/current/?_profile=nvs&_mediatype=application/rdf+xml

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#109]
It returns an empty RDF:
<rdf:RDF
    xmlns:dce="http://purl.org/dc/elements/1.1/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:grg="http://www.isotc211.org/schemas/grg/"
    xmlns:pav="http://purl.org/pav/"
    xmlns:skos="http://www.w3.org/2004/02/skos/core#"
    xmlns:void="http://rdfs.org/ns/void#"></rdf:RDF>

**Comment by nicholascar** [comment]
Fixed a little while back, see http://nvs.surroundaustralia.com/scheme/EMODNET_PEST/current/?_profile=nvs&_mediatype=application/rdf+xml
