### ISSUE TITLE
Replace http://www.w3.org/ns/org# with http://www.w3.org/ns/org#Organization in Mappings data

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocPrez-theme-nvs#111]

**Comment by nicholascar** [comment]
`<x> http://www.w3.org/ns/org# <y>`

`<x> http://www.w3.org/ns/org#Organization <y>`

**Comment by alko-k** [comment]
@nicholascar the internal link we have http://vocab.nerc.ac.uk/mapping/I/234/ uses <x> <http://www.w3.org/ns/org#memberOf> <y> so I plan to use the same. Is that all right?

**Comment by alko-k** [comment]
This is now done in our sparql endpoint using the  http://www.w3.org/ns/org#memberOf

**Comment by nicholascar** [comment]
Done in SPARQL endpoint and seen in data.
