### ISSUE TITLE
Versioning of concepts does not work

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#121]
Hi @nicholascar,
The versioning of concepts does not work.
e.g. http://nvs.surroundaustralia.com/collection/D01/current/D0100001/1/

**Comment by alko-k** [comment]
@nicholascar this is the  highest priority ticket, I would like you to look at.

**Comment by alko-k** [comment]
The information for this is all in the sparql endpoint

**Comment by nicholascar** [comment]
Fixed by https://github.com/surroundaustralia/NvsVocPrez/commit/09b87ec50f8b69837e4c8f565fef13ba3e83e70a
