### ISSUE TITLE
vocab.nerc.ac.uk using Accept: application/rdf+xml

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#122]
The rdf returned contains one surround URL in the bold part

<rdf:Description rdf:about="https://vocab.nerc.ac.uk/">
        <rdf:type rdf:resource="http://www.w3.org/ns/dcat#DataService"/>
        <dcterms:description xml:lang="en">A Content Negotiation by Profile-compliant service that provides access to all of this catalogue's information</dcterms:description>
        <dcterms:title>System ConnegP API</dcterms:title>
        <dcterms:type rdf:resource="http://purl.org/dc/dcmitype/Service"/>
        **<dcat:endpointURL rdf:resource="http://nvs.surroundaustralia.com"/>**
        <dcat:servesDataset rdf:resource="http://vocab.nerc.ac.uk/"/>

**Comment by nicholascar** [comment]
URLs now templated out to reflect the system URL, not a static URL, as per Commit https://github.com/surroundaustralia/NvsVocPrez/commit/e10497d812b468013169d67c1f7ff1131b2bce1b
