### ISSUE TITLE
Add <?xml version="1.0" encoding="UTF-8"?> in  all RDF/XML

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#125]
Is it possible to add this to all of the RDF/XMLs (cocnept/collection/scheme/mapping) <?xml version="1.0" encoding="UTF-8"?>
as the old one contains it and it may break end users systems?

**Comment by alko-k** [comment]
Hi @nicholascar , is it possible to do this one please, as it is crucial for our end users?

**Comment by nicholascar** [comment]
Addressed by Commit https://github.com/surroundaustralia/NvsVocPrez/commit/9ab3b1ccaa83b0076d98d0b9521a51a634a04821

**Comment by alko-k** [comment]
Thank you @nicholascar I can confirm this works and we can close the ticket :-)
