### ISSUE TITLE
Property changes after prod feedback

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocPrez-theme-nvs#52]
> Only the broader mappings are shown for any concept and our users are being worried that the mappings have changed or that we deleted them. And this comes back from all of our users. Could you please add the rest of the mappings in the human interface?

**Comment by nicholascar** [comment]
Missing property:

* skos:related

See http://vocab.nerc.ac.uk/collection/P01/current/TEMPPR01/ for the example.

Also:

One match per related Concept, English prefLabel - see multiple Broaders for http://vocab.nerc.ac.uk/collection/P02/current/DOXY/

**Comment by nicholascar** [comment]
Ordering of properties: 

> could we have first the Same as, then the Broader, then the related then the Narrower?

**Comment by nicholascar** [comment]
`skos:related` catered for, see http://nvs.surroundaustralia.com/collection/P01/current/TEMPPR01/

repeated related properties deduplicated, see http://nvs.surroundaustralia.com/collection/P01/current/TEMPPR01/

ordering as requested catered for, see http://nvs.surroundaustralia.com/collection/P01/current/TEMPPR01/

**Comment by alko-k** [comment]
http://vocabdev.nerc.ac.uk/collection/P01/current/TEMPPR01/ looks good but
http://vocabdev.nerc.ac.uk/collection/P02/current/DOXY/ shows P22 in multiple languages
I can see RELATED in both concepts
I can see the ordering of the same/broader/related/narrower
