### ISSUE TITLE
Remove Ext vocab label from related Concepts

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocPrez-theme-nvs#57]

**Comment by nicholascar** [comment]
Fixed, see http://vocab.nerc.ac.uk/collection/P06/current/UPAA/

**Comment by alko-k** [comment]
http://vocabdev.nerc.ac.uk/collection/P06/current/UPAA/ gives me an internal error
and here: http://nvs.surroundaustralia.com/collection/P06/current/UPAA/
