### ISSUE TITLE
Nicely render JSON Literals and apply rdf:JSON datatype class

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocPrez-theme-nvs#6]
e.g. http://nerc.surroundaustralia.com/object?vocab_uri=http://vocab.nerc.ac.uk/scheme/NETOC_PLACE/current/&uri=http%3A//vocab.nerc.ac.uk/collection/C19/current/9/

**Comment by recalcitrantsupplant** [comment]
Adding "<pre>" (preformatted text) appears to be the nicest method.

The inelegant part is needing to check whether the concept definition to display is json, which I've currently done by looking at the start of the string within the HTML template.

      {% if concept.definition.startswith("{") %}
        <td><pre>{{ concept.definition }}</pre></td>
      {% else %}
        <td>{{ concept.definition }}</td>
      {% endif %}

Was the 'annotations' attribute on 'Concepts' for adding flags? i.e. In source.py I'd check whether the concept.definition is json, and if so, pass this through to the template as a flag in 'annotations'.

**Comment by nicholascar** [comment]
Perhaps you'd better add this logic to the _format.html sub-template:

https://github.com/RDFLib/VocPrez/blob/master/vocprez/view/templates/_format.html

That template was added some time ago but, I think, I removed references to it when I went through the 2.0 upgrade as I was confused about its use - I can't see it imported in concept.html. I think _format.html should be updated and used.

Here is vocabulary.html importing not that one but another template and using it: 

https://github.com/RDFLib/VocPrez/blob/master/vocprez/view/templates/vocabulary.html
