### ISSUE TITLE
Ensure filter posts back to /collection/ & /scheme/ not /vocab/

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocPrez-theme-nvs#63]

**Comment by alko-k** [comment]
Hi @nicholascar 
That one still takes me back to /vocab and the old page

**Comment by nicholascar** [comment]
Ooops sorry, I fixed this then un-fixed it with another commit. I've re-fixed it now, see http://nvs.surroundaustralia.com/collection/
