### ISSUE TITLE
RDF/XML on the concept level

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#79]
Concept's RDF/XML e.g. http://nvs.surroundaustralia.com/collection/P02/current/WVST/?_mediatype=application/rdf+xml looks good. So I see no issues apart from what we have discussed this before  and is related with the mappings links in the concept RDF/XML.
This is part of a project deliverable and cannot be omitted from the XML. 
Any suggestions on how else it could be implemented?

**Comment by alko-k** [comment]
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet href="/VocabV2/Concept2Html.xsl" type="text/xsl" media="screen"?><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:dc="http://purl.org/dc/terms/" xmlns:dce="http://purl.org/dc/elements/1.1/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:void="http://rdfs.org/ns/void#" xmlns:pav="http://purl.org/pav/" xmlns:prov="https://www.w3.org/ns/prov#" xmlns:reg="http://purl.org/linked-data/registry#" xml:base="http://vocab.nerc.ac.uk/collection/W01/current/007/">
<skos:Concept rdf:about="http://vocab.nerc.ac.uk/collection/W01/current/007/">
<skos:prefLabel xml:lang="en">Accuracy</skos:prefLabel>
<skos:altLabel/>
<skos:definition xml:lang="en">Accuracy is closeness of measurement to the true value.</skos:definition>
<dc:date>2014-12-19 00:00:00.0</dc:date>
<dc:identifier>SDN:W01::007</dc:identifier>
<dce:identifier>SDN:W01::007</dce:identifier>
<skos:notation>SDN:W01::007</skos:notation>
<owl:versionInfo>1</owl:versionInfo>
<pav:hasCurrentVersion rdf:resource="http://vocab.nerc.ac.uk/collection/W01/current/007/1/"/>
<pav:version>1</pav:version>
<pav:authoredOn>2014-12-19 00:00:00.0</pav:authoredOn>
<skos:note xml:lang="en">accepted</skos:note>
<owl:deprecated>false</owl:deprecated>
<owl:sameAs **rdf:ID="I877240"** rdf:resource="http://vocab.nerc.ac.uk/collection/W04/current/CAPB0001/"/>
<void:inDataset rdf:resource="http://vocab.nerc.ac.uk/.well-known/void"/>
</skos:Concept>
**<rdf:Description rdf:about="#I877240">
<prov:has_provenance rdf:resource="http://vocab.nerc.ac.uk/mapping/I/877240/"/>
</rdf:Description>**
</rdf:RDF>

**Comment by nicholascar** [comment]
Try using `PREFIX` values in the SPARQL query

**Comment by nicholascar** [comment]
I've matched the reified triples using a `CONSTRUCT` query that explicitly targets `rdf:Statement` instances that reference the subject Concept and have a `prov:has_provenance` triple in them too. This replaces the `DESCRIBE` query I had previously which didn't 'see' the provenance. I've also ensured prefixes are implemented.
