### ISSUE TITLE
Markdown-formatted URL links not recognised?

### ISSUE THREAD

**Issue by gwemon** [surroundaustralia/VocPrez-theme-nvs#81]
I reformatted a  URL using Markdown notation so that it is recognised as an hyperlink when listed out in VocPrez as you recommended @nicholascar but it does not seem to be recognised. Please see http://vocab.nerc.ac.uk/collection/?filter=C31

**Comment by nicholascar** [comment]
![image](https://user-images.githubusercontent.com/7321872/117270324-6fdfc800-ae9c-11eb-88c5-3a9f8b881167.png)

**Comment by nicholascar** [comment]
I've fixed the font sizing issue (text in Markdown/HTML paragraphs was smaller that other text), so this is done.
