### ISSUE TITLE
http://nvs.surroundaustralia.com/ is down

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#88]
Hi @nicholascar  bringing the http://nvs.surroundaustralia.com/ up this is one of the priorities for this sprint that starts on Tuesday 22/06/2021, so we can test.

I cannot assign this ticket to a project though

**Comment by nicholascar** [comment]
Try now!

**Comment by alko-k** [comment]
Haha thanks Nick, it works now :-)
