### ISSUE TITLE
grg:RE_RegisterOwner gets wrong values

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#94]
Nick grg:RE_RegisterOwner  possible picks up wrong vaues.
e.g. R25 grg:RE_RegisterOwner is Argo Data management Team while nvs.surroundaustralia.com shows British Oceanographic Data Centre
Or V22 has grg:RE_RegisterOwner SeaDataNet but surroundaustralia shows British Oceanographic Data Centre

That is when I get the RDF/XML from http://nvs.surroundaustralia.com/collection/

**Comment by nicholascar** [comment]
Resolved see http://nvs.surroundaustralia.com/collection/
