### ISSUE TITLE
Download RDF/XML for http://nvs.surroundaustralia.com/collection/A05/current/: weird character in skos:definition

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#95]
When downloading the whole http://nvs.surroundaustralia.com/collection/A05/current/ vocabulary via RDF/XML the following concept (did not check for others) has a weird A character where it is bold. 

http://vocab.nerc.ac.uk/collection/A05/current/EV_SEATEMP/
<skos:definition xml:lang="en">The temperature **ofÂ** seawater expressed against the International Temperature Scale 1990 (ITS-90) standard.</skos:definition>
			</skos:Concept>
The same character appears when you try to download the RDF/XMl of the concept  too http://nvs.surroundaustralia.com/collection/A05/current/EV_SEATEMP/

**Comment by nicholascar** [comment]
Solved through use of triplestore's native encoding, see http://nvs.surroundaustralia.com/collection/A05/current/
