### ISSUE TITLE
http://nvs.surroundaustralia.com/mapping/E/177178/?_profile=nvs&_mediatype=application/rdf+xml giving a 500 error while turtle/html is all right

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#98]

**Comment by alko-k** [comment]
@nicholascar  I cannot assign projects to the issues. I probably don't have the permissions to do so.

**Comment by nicholascar** [comment]
No worries, I can keep doing that.

**Comment by nicholascar** [comment]
Two problems, both solved:

1. VP didn't handle /E/, now does
2. triplestore data has erroneous use of the ORG namespace like this: `<x> <http://www.w3.org/ns/org#> <y>` when it should be `<x> <http://www.w3.org/ns/org#Organization> <y>`. This was breaking the XML serialization. I've patched this for now but the data needs to be updated, see Issue #111
