### ISSUE TITLE
http://nvs.surroundaustralia.com/standard_name/?_profile=nvs&_mediatype=application/rdf+xml times out

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#99]

**Comment by alko-k** [comment]
Here is what we get in BODC when I try to get the RDF/XML: Error 400: Failed to write output in RDF/XML: Only well-formed absolute URIrefs can be included in RDF/XML output: <c> Code: 57/REQUIRED_COMPONENT_MISSING in SCHEME: A component that is required by the scheme is missing.

**Comment by nicholascar** [comment]
Resolved see http://nvs.surroundaustralia.com/standard_name/?_profile=nvs&_mediatype=application/rdf+xml
